-- Gerado por scripts/generate-comms-seed.ts a partir de src/data/office.ts.
-- Idempotente (ON CONFLICT DO NOTHING).

INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm1', '00000000-0000-0000-0000-000000000001', 'c1', 'cm1-thread', 'Ana Beatriz', 'WhatsApp', 'Recebida', 'Documentos do fechamento', 'Preciso enviar os documentos do fechamento.', 'Preciso enviar os documentos do fechamento.', 'Média', 'Neutro', 'Solicitação', 'Pedro Lima', 'Aguardando cliente', true, 'Solicitação relacionada ao fechamento mensal.', '2026-09-01'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm2', '00000000-0000-0000-0000-000000000001', 'c2', 'cm2-thread', 'Carlos Menezes', 'E-mail', 'Recebida', 'Dúvida sobre guia do DAS', 'Bom dia! Poderiam confirmar o valor da guia do DAS deste mês?', 'Bom dia! Poderiam confirmar o valor da guia do DAS deste mês?', 'Média', 'Neutro', 'Documento', 'Bianca Souza', 'Respondida', false, 'Solicitação relacionada a documentos — coletar ou enviar o que foi pedido.', '2026-09-02'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm3', '00000000-0000-0000-0000-000000000001', 'c3', 'cm3-thread', 'Fernanda Dias', 'WhatsApp', 'Recebida', 'Guia com valor errado', 'A guia veio com o valor errado, isso já é a segunda vez que acontece.', 'A guia veio com o valor errado, isso já é a segunda vez que acontece.', 'Alta', 'Negativo', 'Reclamação', 'Tiago Rocha', 'Resolvida', false, 'Reclamação do cliente — analisar e responder com prioridade.', '2026-09-03'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm4', '00000000-0000-0000-0000-000000000001', 'c4', 'cm4-thread', 'Pedro Lima', 'E-mail', 'Enviada', 'Boleto não baixado', 'O boleto do mês passado ainda não foi baixado, podem verificar?', 'O boleto do mês passado ainda não foi baixado, podem verificar?', 'Média', 'Neutro', 'Cobrança', 'Maria Souza', 'Novo', true, 'Assunto financeiro — encaminhar ao time de cobrança.', '2026-09-04'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm5', '00000000-0000-0000-0000-000000000001', 'c5', 'cm5-thread', 'Juliana Alves', 'Portal', 'Recebida', 'Interesse em BPO financeiro', 'Gostaria de saber mais sobre contratar o serviço de BPO financeiro para minha empresa.', 'Gostaria de saber mais sobre contratar o serviço de BPO financeiro para minha empresa.', 'Média', 'Positivo', 'Comercial', 'Lucas Prado', 'Em andamento', true, 'Interesse comercial — encaminhar para o time comercial.', '2026-09-05'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm6', '00000000-0000-0000-0000-000000000001', 'c6', 'cm6-thread', 'Ana Beatriz', 'WhatsApp', 'Recebida', 'Urgente: rescisão de funcionário', 'Isso é urgente, preciso de retorno hoje mesmo sobre a rescisão do funcionário.', 'Isso é urgente, preciso de retorno hoje mesmo sobre a rescisão do funcionário.', 'Crítica', 'Negativo', 'Urgente', 'Camila Nunes', 'Aguardando cliente', true, 'Cliente sinalizou urgência — priorizar atendimento.', '2026-09-06'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm7', '00000000-0000-0000-0000-000000000001', 'c7', 'cm7-thread', 'Carlos Menezes', 'E-mail', 'Recebida', 'Extrato bancário — agosto', 'Segue em anexo o extrato bancário de agosto.', 'Segue em anexo o extrato bancário de agosto.', 'Média', 'Neutro', 'Documento', 'Eduardo Reis', 'Respondida', false, 'Solicitação relacionada a documentos — coletar ou enviar o que foi pedido.', '2026-09-07'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm8', '00000000-0000-0000-0000-000000000001', 'c8', 'cm8-thread', 'Fernanda Dias', 'WhatsApp', 'Recebida', 'Agradecimento', 'Muito obrigado pelo atendimento, ficou tudo certo!', 'Muito obrigado pelo atendimento, ficou tudo certo!', 'Baixa', 'Positivo', 'Outros', 'Patrícia Gomes', 'Resolvida', false, 'Feedback positivo do cliente — nenhuma ação necessária.', '2026-09-08'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm9', '00000000-0000-0000-0000-000000000001', 'c9', 'cm9-thread', 'Camila Nunes', 'Portal', 'Enviada', 'Dúvida sobre Simples Nacional', 'Poderiam me explicar como funciona o cálculo do Simples Nacional?', 'Poderiam me explicar como funciona o cálculo do Simples Nacional?', 'Baixa', 'Neutro', 'Dúvida', 'Vitor Andrade', 'Novo', true, 'Dúvida do cliente — responder com a explicação necessária.', '2026-09-09'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm10', '00000000-0000-0000-0000-000000000001', 'c10', 'cm10-thread', 'Juliana Alves', 'E-mail', 'Recebida', 'Negociação de boleto vencido', 'Precisamos negociar o boleto vencido do mês passado.', 'Precisamos negociar o boleto vencido do mês passado.', 'Média', 'Neutro', 'Cobrança', 'Ana Beatriz', 'Em andamento', true, 'Assunto financeiro — encaminhar ao time de cobrança.', '2026-09-10'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm11', '00000000-0000-0000-0000-000000000001', 'c11', 'cm11-thread', 'Patrícia Gomes', 'Mensagem interna', 'Enviada', 'Checklist do fechamento', 'Equipe, revisar o checklist do fechamento deste cliente antes de enviar.', 'Equipe, revisar o checklist do fechamento deste cliente antes de enviar.', 'Baixa', 'Neutro', 'Outros', 'Carlos Menezes', 'Aguardando cliente', false, 'Sem ação clara identificada — revisar manualmente.', '2026-09-11'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm12', '00000000-0000-0000-0000-000000000001', 'c12', 'cm12-thread', 'Carlos Menezes', 'Portal', 'Recebida', 'Segunda via do contrato social', 'Gostaria de solicitar a segunda via do contrato social.', 'Gostaria de solicitar a segunda via do contrato social.', 'Média', 'Neutro', 'Solicitação', 'Fernanda Dias', 'Respondida', false, 'Solicitação do cliente — encaminhar para o responsável.', '2026-09-12'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm13', '00000000-0000-0000-0000-000000000001', 'c13', 'cm13-thread', 'Fernanda Dias', 'E-mail', 'Recebida', 'Demora no suporte', 'Reclamação: o suporte demorou 3 dias para responder minha última mensagem.', 'Reclamação: o suporte demorou 3 dias para responder minha última mensagem.', 'Alta', 'Negativo', 'Reclamação', 'João Ferreira', 'Resolvida', false, 'Reclamação do cliente — analisar e responder com prioridade.', '2026-09-13'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm14', '00000000-0000-0000-0000-000000000001', 'c14', 'cm14-thread', 'Carlos Menezes', 'WhatsApp', 'Enviada', 'Guia de FGTS', 'Podem enviar a guia de FGTS deste mês assim que possível?', 'Podem enviar a guia de FGTS deste mês assim que possível?', 'Média', 'Neutro', 'Documento', 'Marina Costa', 'Novo', true, 'Solicitação relacionada a documentos — coletar ou enviar o que foi pedido.', '2026-09-14'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm15', '00000000-0000-0000-0000-000000000001', 'c15', 'cm15-thread', 'Juliana Alves', 'E-mail', 'Recebida', 'Confirmação de recebimento', 'Favor confirmar o recebimento das notas fiscais enviadas ontem.', 'Favor confirmar o recebimento das notas fiscais enviadas ontem.', 'Média', 'Neutro', 'Solicitação', 'Rodrigo Melo', 'Em andamento', true, 'Solicitação do cliente — encaminhar para o responsável.', '2026-09-15'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm16', '00000000-0000-0000-0000-000000000001', 'c16', 'cm16-thread', 'Ana Beatriz', 'Portal', 'Recebida', 'Dúvida sobre relatório gerencial', 'Ficamos com uma dúvida sobre o relatório gerencial, poderia explicar a variação de custos?', 'Ficamos com uma dúvida sobre o relatório gerencial, poderia explicar a variação de custos?', 'Baixa', 'Neutro', 'Dúvida', 'Pedro Lima', 'Aguardando cliente', true, 'Dúvida do cliente — responder com a explicação necessária.', '2026-09-16'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm17', '00000000-0000-0000-0000-000000000001', 'c17', 'cm17-thread', 'Marina Costa', 'Mensagem interna', 'Enviada', 'Oportunidade de consultoria', 'Equipe, cliente sinalizou interesse em consultoria tributária — avaliar oportunidade.', 'Equipe, cliente sinalizou interesse em consultoria tributária — avaliar oportunidade.', 'Média', 'Positivo', 'Comercial', 'Bianca Souza', 'Respondida', false, 'Interesse comercial — encaminhar para o time comercial.', '2026-09-17'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.communications (id, workspace_id, client_id, thread_id, sender, channel, direction, subject, content, summary, priority, sentiment, classification, assignee, status, requires_action, suggested_action, created_at)
VALUES ('cm18', '00000000-0000-0000-0000-000000000001', 'c18', 'cm18-thread', 'Fernanda Dias', 'Portal', 'Recebida', 'Documentos do fechamento — prazo', 'Preciso enviar os documentos do fechamento, mas só consigo até sexta-feira.', 'Preciso enviar os documentos do fechamento, mas só consigo até sexta-feira.', 'Média', 'Neutro', 'Solicitação', 'Tiago Rocha', 'Resolvida', false, 'Solicitação relacionada ao fechamento mensal.', '2026-09-18'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.announcements (id, workspace_id, title, body, audience, published_at)
VALUES ('an1', '00000000-0000-0000-0000-000000000001', 'Prazo da DAS de setembro', 'A guia do DAS de setembro vence no dia 20/09. Envie os documentos pendentes até o dia 17 para garantirmos a apuração em tempo.', 'Todos os clientes', '2026-09-10'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.announcements (id, workspace_id, title, body, audience, published_at)
VALUES ('an2', '00000000-0000-0000-0000-000000000001', 'Novo canal de atendimento pelo Portal', 'Agora você pode enviar documentos e mensagens direto pelo Portal do Cliente, sem precisar de e-mail ou WhatsApp. O prazo de resposta é o mesmo dos outros canais.', 'Todos os clientes', '2026-09-05'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.announcements (id, workspace_id, title, body, audience, published_at)
VALUES ('an3', '00000000-0000-0000-0000-000000000001', 'Atualização no eSocial para a Folha', 'O eSocial passou a exigir confirmação de admissões e desligamentos até o 5º dia útil do mês seguinte. Fique atento às solicitações de confirmação enviadas pelo nosso time.', 'Pessoal', '2026-09-02'::timestamptz)
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.announcements (id, workspace_id, title, body, audience, published_at)
VALUES ('an4', '00000000-0000-0000-0000-000000000001', 'Horário de atendimento no feriado', 'No feriado de 7 de setembro não haverá atendimento. Retornamos normalmente no dia 8, com prioridade para prazos que vencerem no período.', 'Todos os clientes', '2026-08-28'::timestamptz)
ON CONFLICT (id) DO NOTHING;

